[2025-03-01T16:01:11.580+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_quality_pipeline.check_quality_success_flag scheduled__2025-02-28T00:00:00+00:00 [queued]>
[2025-03-01T16:01:11.588+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_quality_pipeline.check_quality_success_flag scheduled__2025-02-28T00:00:00+00:00 [queued]>
[2025-03-01T16:01:11.588+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-03-01T16:01:11.601+0000] {taskinstance.py:1327} INFO - Executing <Task(BranchPythonOperator): check_quality_success_flag> on 2025-02-28 00:00:00+00:00
[2025-03-01T16:01:11.606+0000] {standard_task_runner.py:57} INFO - Started process 263 to run task
[2025-03-01T16:01:11.610+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_quality_pipeline', 'check_quality_success_flag', 'scheduled__2025-02-28T00:00:00+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/data_quality_pipeline.py', '--cfg-path', '/tmp/tmpfbwbcd0r']
[2025-03-01T16:01:11.618+0000] {standard_task_runner.py:85} INFO - Job 172: Subtask check_quality_success_flag
[2025-03-01T16:01:11.720+0000] {task_command.py:410} INFO - Running <TaskInstance: data_quality_pipeline.check_quality_success_flag scheduled__2025-02-28T00:00:00+00:00 [running]> on host f8650cbaf99d
[2025-03-01T16:01:11.818+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_quality_pipeline' AIRFLOW_CTX_TASK_ID='check_quality_success_flag' AIRFLOW_CTX_EXECUTION_DATE='2025-02-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-28T00:00:00+00:00'
[2025-03-01T16:01:11.822+0000] {python.py:183} INFO - Done. Returned value was: validate_data
[2025-03-01T16:01:11.822+0000] {python.py:216} INFO - Branch callable return validate_data
[2025-03-01T16:01:11.823+0000] {skipmixin.py:164} INFO - Following branch validate_data
[2025-03-01T16:01:11.842+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 217, in execute
    self.skip_all_except(context["ti"], branch)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/skipmixin.py", line 199, in skip_all_except
    "'branch_task_ids' must contain only valid task_ids. "
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'validate_data'}.
[2025-03-01T16:01:11.850+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=data_quality_pipeline, task_id=check_quality_success_flag, execution_date=20250228T000000, start_date=20250301T160111, end_date=20250301T160111
[2025-03-01T16:01:11.870+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 172 for task check_quality_success_flag ('branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'validate_data'}.; 263)
[2025-03-01T16:01:11.913+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-03-01T16:01:11.947+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
